using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;

namespace WinUI3RisohEditor.ResourceParsers
{
    /// <summary>
    /// Parser for Windows Resource Script (.rc) files
    /// </summary>
    public class RCParser
    {
        public static List<ResourceNode> Parse(string content)
        {
            var resources = new List<ResourceNode>();
            var lines = content.Split('\n');
            var currentResource = new StringBuilder();
            string? currentType = null;
            string? currentName = null;
            bool inBlock = false;
            int braceCount = 0;

            foreach (var rawLine in lines)
            {
                var line = rawLine.Trim();

                // Skip comments and empty lines
                if (string.IsNullOrWhiteSpace(line) || line.StartsWith("//"))
                    continue;

                // Detect resource start
                if (!inBlock)
                {
                    // Try to match resource definition patterns
                    // Format: NAME TYPE [options]
                    var match = Regex.Match(line, @"^(\w+)\s+(DIALOG|MENU|ICON|BITMAP|CURSOR|ACCELERATORS|STRINGTABLE|VERSIONINFO|RCDATA)");
                    if (match.Success)
                    {
                        // Save previous resource if exists
                        if (!string.IsNullOrEmpty(currentName) && !string.IsNullOrEmpty(currentType))
                        {
                            resources.Add(new ResourceNode
                            {
                                Name = currentName,
                                Type = currentType,
                                Content = currentResource.ToString()
                            });
                        }

                        currentName = match.Groups[1].Value;
                        currentType = match.Groups[2].Value;
                        currentResource.Clear();
                        currentResource.AppendLine(line);

                        if (line.Contains("{"))
                        {
                            inBlock = true;
                            braceCount = line.Count(c => c == '{') - line.Count(c => c == '}');
                        }
                        else if (currentType == "ICON" || currentType == "BITMAP" || currentType == "CURSOR")
                        {
                            // These are typically single-line file references
                            inBlock = false;
                        }
                        continue;
                    }
                }

                if (inBlock || currentResource.Length > 0)
                {
                    currentResource.AppendLine(line);

                    braceCount += line.Count(c => c == '{');
                    braceCount -= line.Count(c => c == '}');

                    if (braceCount == 0 && line.Contains("}"))
                    {
                        inBlock = false;
                    }
                }
            }

            // Save last resource
            if (!string.IsNullOrEmpty(currentName) && !string.IsNullOrEmpty(currentType))
            {
                resources.Add(new ResourceNode
                {
                    Name = currentName,
                    Type = currentType,
                    Content = currentResource.ToString()
                });
            }

            return resources;
        }

        public static string Generate(IEnumerable<ResourceNode> resources)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// Resource Script File");
            sb.AppendLine("// Generated by RisohEditor - WinUI3");
            sb.AppendLine();
            sb.AppendLine("#include \"resource.h\"");
            sb.AppendLine();

            // Group by type
            foreach (var group in resources.GroupBy(r => r.Type))
            {
                sb.AppendLine($"////////////////////////////////////////////////////////////////////////////");
                sb.AppendLine($"// {group.Key}");
                sb.AppendLine();

                foreach (var resource in group)
                {
                    sb.AppendLine(resource.Content ?? string.Empty);
                    sb.AppendLine();
                }
            }

            return sb.ToString();
        }

        /// <summary>
        /// Parse STRINGTABLE resources
        /// </summary>
        public static Dictionary<int, string> ParseStringTable(string content)
        {
            var strings = new Dictionary<int, string>();
            var lines = content.Split('\n');
            var inTable = false;

            foreach (var line in lines)
            {
                var trimmed = line.Trim();

                if (trimmed.Contains("STRINGTABLE"))
                {
                    inTable = true;
                    continue;
                }

                if (inTable)
                {
                    if (trimmed.Contains("{"))
                        continue;

                    if (trimmed.Contains("}"))
                    {
                        inTable = false;
                        continue;
                    }

                    // Parse string entry: ID "String"
                    var match = Regex.Match(trimmed, @"^(\w+)\s+""(.*)""");
                    if (match.Success)
                    {
                        var idStr = match.Groups[1].Value;
                        var text = match.Groups[2].Value;

                        // Try to parse ID as integer or resolve from constant
                        if (int.TryParse(idStr, out int id))
                        {
                            strings[id] = text;
                        }
                    }
                }
            }

            return strings;
        }

        /// <summary>
        /// Parse MENU resources
        /// </summary>
        public static MenuResource ParseMenu(string content)
        {
            var menu = new MenuResource();
            var lines = content.Split('\n');
            var stack = new Stack<MenuItemNode>();
            MenuItemNode? currentItem = null;

            foreach (var line in lines)
            {
                var trimmed = line.Trim();

                if (trimmed.Contains("MENU"))
                    continue;

                if (trimmed.Contains("{"))
                {
                    if (currentItem != null)
                        stack.Push(currentItem);
                    continue;
                }

                if (trimmed.Contains("}"))
                {
                    if (stack.Count > 0)
                        stack.Pop();
                    continue;
                }

                // Parse menu items
                if (trimmed.StartsWith("POPUP"))
                {
                    var match = Regex.Match(trimmed, @"POPUP\s+""(.*)""");
                    if (match.Success)
                    {
                        currentItem = new MenuItemNode
                        {
                            Text = match.Groups[1].Value,
                            IsPopup = true
                        };

                        if (stack.Count > 0)
                            stack.Peek().Children.Add(currentItem);
                        else
                            menu.Items.Add(currentItem);
                    }
                }
                else if (trimmed.StartsWith("MENUITEM"))
                {
                    if (trimmed.Contains("SEPARATOR"))
                    {
                        var separator = new MenuItemNode { IsSeparator = true };
                        if (stack.Count > 0)
                            stack.Peek().Children.Add(separator);
                    }
                    else
                    {
                        var match = Regex.Match(trimmed, @"MENUITEM\s+""(.*)"",\s*(\w+)");
                        if (match.Success)
                        {
                            var item = new MenuItemNode
                            {
                                Text = match.Groups[1].Value,
                                CommandId = match.Groups[2].Value
                            };

                            if (stack.Count > 0)
                                stack.Peek().Children.Add(item);
                            else
                                menu.Items.Add(item);
                        }
                    }
                }
            }

            return menu;
        }

        /// <summary>
        /// Parse DIALOG resources
        /// </summary>
        public static DialogResource ParseDialog(string content)
        {
            var dialog = new DialogResource();
            var lines = content.Split('\n');

            foreach (var line in lines)
            {
                var trimmed = line.Trim();

                // Parse dialog definition
                var dialogMatch = Regex.Match(trimmed, @"DIALOG\s+(\d+),\s*(\d+),\s*(\d+),\s*(\d+)");
                if (dialogMatch.Success)
                {
                    dialog.X = int.Parse(dialogMatch.Groups[1].Value);
                    dialog.Y = int.Parse(dialogMatch.Groups[2].Value);
                    dialog.Width = int.Parse(dialogMatch.Groups[3].Value);
                    dialog.Height = int.Parse(dialogMatch.Groups[4].Value);
                    continue;
                }

                // Parse CAPTION
                var captionMatch = Regex.Match(trimmed, @"CAPTION\s+""(.*)""");
                if (captionMatch.Success)
                {
                    dialog.Caption = captionMatch.Groups[1].Value;
                    continue;
                }

                // Parse FONT
                var fontMatch = Regex.Match(trimmed, @"FONT\s+(\d+),\s*""(.*)""");
                if (fontMatch.Success)
                {
                    dialog.FontSize = int.Parse(fontMatch.Groups[1].Value);
                    dialog.FontName = fontMatch.Groups[2].Value;
                    continue;
                }

                // Parse controls (simplified)
                var controlMatch = Regex.Match(trimmed, @"(PUSHBUTTON|DEFPUSHBUTTON|EDITTEXT|LTEXT|RTEXT|CTEXT|GROUPBOX|CHECKBOX|RADIOBUTTON|COMBOBOX|LISTBOX)\s+""(.*)"",\s*(\w+),\s*(\d+),\s*(\d+),\s*(\d+),\s*(\d+)");
                if (controlMatch.Success)
                {
                    dialog.Controls.Add(new DialogControl
                    {
                        Type = controlMatch.Groups[1].Value,
                        Text = controlMatch.Groups[2].Value,
                        Id = controlMatch.Groups[3].Value,
                        X = int.Parse(controlMatch.Groups[4].Value),
                        Y = int.Parse(controlMatch.Groups[5].Value),
                        Width = int.Parse(controlMatch.Groups[6].Value),
                        Height = int.Parse(controlMatch.Groups[7].Value)
                    });
                }
            }

            return dialog;
        }
    }

    // Supporting classes for parsed resources
    public class MenuResource
    {
        public List<MenuItemNode> Items { get; set; } = new();
    }

    public class MenuItemNode
    {
        public string Text { get; set; } = string.Empty;
        public string CommandId { get; set; } = string.Empty;
        public bool IsPopup { get; set; }
        public bool IsSeparator { get; set; }
        public List<MenuItemNode> Children { get; set; } = new();
    }

    public class DialogResource
    {
        public int X { get; set; }
        public int Y { get; set; }
        public int Width { get; set; }
        public int Height { get; set; }
        public string Caption { get; set; } = string.Empty;
        public int FontSize { get; set; }
        public string FontName { get; set; } = string.Empty;
        public List<DialogControl> Controls { get; set; } = new();
    }

    public class DialogControl
    {
        public string Type { get; set; } = string.Empty;
        public string Text { get; set; } = string.Empty;
        public string Id { get; set; } = string.Empty;
        public int X { get; set; }
        public int Y { get; set; }
        public int Width { get; set; }
        public int Height { get; set; }
    }
}
